services:
  dns-server:
    container_name: dns-server
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: dns-server:${TAG:-latest}
    entrypoint: /docker-entrypoint.sh
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh:rw
      - ./conf:/conf:ro
    network_mode: "host"
